### ISSUE TITLE
Any word on Rails 4 / Strong Parameters?

### ISSUE THREAD

**Issue by coreyward** [assembler/attachinary#88]
There appears to be an omission of integrating with Rails 4 — what parameters need to be permitted for Attachinary to work correctly?

**Comment by bkubic** [comment]
I'm having trouble getting around this issue - the photos get uploaded to Cloudinary, but their data isn't stored in the local database so I can't call them later. Could someone walk be through step by step how to set up the monkey patch? I have a very basic model (House) while has many photo attachments.

**Comment by milesmatthias** [comment]
Is there a reason @spitzer's batch hasn't been merged in?

**Comment by fabianoleittes** [comment]
Hi guys!!
Any solution to the problem of Strong Parameters(mass-assign protected attributes) ?

I'm using rails version 4.2.3


found unpermitted parameters: signature, created_at, tags, bytes, type, etag, url, secure_url, original_filename

**Comment by coreyward** [comment]
Hey @fabianoleittes, 

The easiest way (barring @assembler merging @spitzer's pull request), is to update your Gemfile to use the following:

    gem 'attachinary', github: 'spitzer/attachinary', ref: 'd65f15e26844c4253e8359d5c2b750a50f52afbd'

After changing, be sure to run `bundle update` and restart your app and you should be smooth sailing.

**Comment by tocker** [comment]
Hi All,

Thanks for reporting, tracking and contributing information on this issue.
I've update the code with a solution.
Can you get the code latest from `master` and retest?

Thanks!

**Comment by stebo** [comment]
Works with the current version so just including gem 'attachinary' is fine.
But you should definitely add this to the readme and explain users, that they have to adjust their def xyz_params function according to has_attachments... took me a lot of time to figure out why no entry was saved into my attachinary_files table!

**Comment by coreyward** [comment]
@stebo That's the problem that's fixed in master. You shouldn't have to adjust your permitted params.

**Comment by stebo** [comment]
@coreyward does not work for me so far: I use
gem 'attachinary', github: 'assembler/attachinary', ref: '3ba29a56e32a83eba5ef024d70c10d709ab68e4a'
than having a "has_attachment  :preview"
and NOT adding :preview to the .permit(...) I still get the error
"Unpermitted parameters: preview" -> attachment is not saved in DB

**Comment by spitzer** [comment]
thanks for the work on this. much appreciated.

gem 'attachinary', github: 'assembler/attachinary', ref: '3ba29a56e32a83eba5ef024d70c10d709ab68e4a'

as expected:
params.require(:user).permit(:photo)
=>
found unpermitted parameters: (ATTRIBUTES I'VE ADDED TO MY USER MODEL)

however:
      params.require(:user).permit(:photo,
                                   (ATTRIBUTES I'VE ADDED TO MY USER MODEL)
                                  )
=>
found unpermitted parameters: signature, created_at, tags, bytes, type, etag, url, secure_url, original_filename

true even if i permit :photo after my custom attributes

so the issue may relate to the addition of attributes to Devise's User model.

**Comment by bbnnt** [comment]
damn it, was stuck on this one (using nested form with cocoon, having attachments in the nested element)

have to say `params.require(:YOUR_MODEL_NAME).permit(:cover_image, {images: []})`works

**Comment by spitzer** [comment]
@tocker, @assembler Hoping someone can take a look at my comment above.
